name: student_assistant_app
description: Student Assistant Application System - TPG316C Group Assignment

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Backend - Supabase
  supabase_flutter: ^2.3.4

  # File Picker (for supporting documents)
  file_picker: ^8.0.0+1
  url_launcher: ^6.2.6

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true